### ISSUE TITLE
🌐 Implement FoundZone

### ISSUE THREAD

**Issue by ccamel** [okp4/contracts#331]
## Purpose

Implement the `ExecuteMsg::FoundZone` message according to the current specification of the `okp4-dataverse` smart contract.

- [ ] Consider the business rules and invariants required for data integrity, security and adherence to specification
- [ ] Implement
- [ ] Test

**Comment by amimart** [comment]
Will be achieved through [#332](https://github.com/okp4/contracts/issues/332)
