### ISSUE TITLE
Improve README.md (emojis + quality section)

### ISSUE THREAD

**Issue by ccamel** [okp4/contracts#341]
## Purpose

The `README.md` file could be enhanced in the following ways:

- [x] Emojis are used for some section headers, but not all. It would be beneficial to add emojis to the remaining section titles for consistency.

<p align="center">
<img width="300" alt="image" src="https://github.com/okp4/contracts/assets/9574336/b8642105-870a-40fe-97eb-ae027c4556a4">
</p>

- [x] A section should be added to describe the quality assurance approach used in this project, which ensures that the Smart Contracts developed meet high-quality standards. The section should especially mention that this is achieved through:
  - The enforcement of stringent rules, monitored by a linter (Clippy) within the Github CI environment.
  - A high level of code coverage through systematic unit testing.
  - Future considerations for additional testing approaches, such as fuzzy testing or end-to-end testing, to further enhance quality.

**Comment by jeremylgn** [comment]
https://github.com/okp4/contracts/pull/384 :ballot_box_with_check:
