### ISSUE TITLE
🔨 Bump `okp4d` version in local chain setup

### ISSUE THREAD

**Issue by amimart** [okp4/contracts#385]
## Description

The current cargo make targets managing the local `okp4d` chain start are running the `v4.0.0` version, we should upgrade to the [v5.0.0](https://github.com/okp4/okp4d/releases/tag/v5.0.0) version.

Unfortunately with this version the transaction broadcast mode doesn't support `block` anymore, a trick will be needed.

**Comment by bdeneux** [comment]
An alternative to `block` mode has been added in the [last release](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.47.5) of cosmos-sdk 😍. But for use it, we need to release a new version of `okp4d` with this new cosmos-sdk. 

I suggest to add a temporary fix by using `sleep` command, and once `okp4d` will be updated, use this new available command to wait transaction response.
