### ISSUE TITLE
Document `okp4-dataverse` Smart Contract in README.md

### ISSUE THREAD

**Issue by ccamel** [okp4/contracts#412]
## Context

With the initial introduction of the [okp4-dataverse smart contract](https://github.com/okp4/contracts/pull/321), it's time to provide a short presentation for it in the `README.md`.

## Todo

- [ ] Make a *card* for the Smart Contract, similar to the other smart contracts:

<img  width="250" src="https://github.com/okp4/contracts/raw/main/etc/objectarium.webp" alt="objectarium" /><img  width="250" src="https://github.com/okp4/contracts/raw/main/etc/cognitarium.webp" alt="cognitarium" /><img  width="250" src="https://github.com/okp4/contracts/raw/main/etc/law-stone.webp" alt="law-stone" />

- [x] Add description to the README.md

**Comment by MdechampG** [comment]
The illustrations are here : https://files.okp4.com/f/368963 but only in png. @JulienMassonnat is it you or Lisa who did them ?

**Comment by ccamel** [comment]
@MdechampG Any progress on that one?

**Comment by MdechampG** [comment]
@JulienMassonnat told me that he will do it.

**Comment by ccamel** [comment]
@JulienMassonnat Love it :heart_eyes:

**Comment by JulienMassonnat** [comment]
Thanks ! I added more black to make it more readable.
![Carte_dataverse_V2](https://github.com/okp4/contracts/assets/63841183/c2237037-87f4-4418-8c09-e4f0289569e2)

**Comment by ccamel** [comment]
@JulienMassonnat Can you adjust texts with the following content:

- Class: `Resource management`
- Kind: `Guardian` or `Custodian`..
- State: `Mutable`
- Dependencies: `Cognitarium, Law-stone`

thanks :pray:

**Comment by MdechampG** [comment]
Yes I love it too !

**Comment by JulienMassonnat** [comment]
Here is the last version
![Carte_dataverse_V3](https://github.com/okp4/contracts/assets/63841183/04d27b1a-b5c7-4059-a48e-3eb30220033b)

**Comment by JulienMassonnat** [comment]
a last one with a small update
![Carte_dataverse_V4_Plan de travail 1](https://github.com/okp4/contracts/assets/63841183/24f2b6f8-c959-4cd3-be92-532453cd060b)

**Comment by JulienMassonnat** [comment]
Incubating version
![Carte_dataverse_V6](https://github.com/okp4/contracts/assets/63841183/d6345acb-3d93-4778-a01f-12f4ebb1c879)
